spring.datasource.url=jdbc:postgresql://localhost:5432/medicarehub
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=A3f$Tz9#Qm2@Lk7!Vr5&Xb8*Wn4^Yp1Jc

# full error logs
logging.level.org.springframework.security=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always